#
# NOTE: this runs the omnibus cookbook, but does not actually run Omnibus. Use
# 'kichen converge' to setup the virtual machine and then `kitchen login` to
# SSH into the machine and run Omnibus.
#

driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['.', '/home/vagrant/omnibus-mcollective']
    - ['../omnibus', '/home/vagrant/omnibus']
    - ['../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.2

platforms:
  - name: centos-5.10
    run_list: yum-epel::default
  - name: centos-6.5
    run_list: yum-epel::default
  - name: debian-7.2.0
    run_list: apt::default
  - name: debian-7.4
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-12.10
    run_list: apt::default
  - name: ubuntu-13.04
    run_list: apt::default
  - name: ubuntu-13.10
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

attribute_defaults: &attribute_defaults
  build_user:          vagrant
  build_user_group:    vagrant
  build_user_password: vagrant

suites:
  - name: chef
    attributes:
      omnibus:
        <<: *attribute_defaults
        install_dir: /opt/chef
    run_list:
      - omnibus::default
